/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.peea.mx.FF.iFrame;


import com.peea.mx.FF.Serial.LecturaSer;
import com.peea.mx.FF.utils.reloj;
import com.peea.mx.FF.utils.tablaChida;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.LinkedList;
import javax.swing.JTable;
import org.jfree.data.xy.XYSeries;

/**
 *
 * @author Sistemas
 */
public class medicioniFrame extends javax.swing.JInternalFrame {

    public LecturaSer ls;
    public tablaChida tc;
    public JTable jtable;
    private String com;
    private int vel;
    public tablasSeparadasiFrame tsi;
    public LinkedList jt,med;
    public XYSeries[] series;
    public String[] valor = {"Espesor", "Tolerancia (-)", "Tolerancia (+)", "Estilo", "Cliente ", "P.O #", "Pieza",
        "Peso"};
    reloj r;

    public String getCom() {
        return com;
    }

    public int getVel() {
        return vel;
    }

    public void setVel(int vel) {
        this.vel = vel;
    }

    public void setCom(String com) {
        this.com = com;
    }

    public medicioniFrame(String com, int vel,tablaChida tc,JTable jta,tablasSeparadasiFrame tsi) {
        initComponents();
        this.com=com;
        this.vel=vel;
        this.tc=tc;
        this.jtable=jta;
        this.tsi=tsi;
        r = new reloj(lblHora);
        r.start();
        jt = new LinkedList();
        jt.add(txtEspesorIn);
        jt.add(txtToleranciaNegIn);
        jt.add(txtToleranciaPosIn);
        jt.add(txtEstilo);
        jt.add(txtCliente);
        jt.add(txtPO);
        jt.add(txtPieza);
        jt.add(txtPeso);
        
        Date hoy = new Date();
        SimpleDateFormat s = new SimpleDateFormat("dd/MM/yyyy");
        lblFecha.setText(s.format(hoy));
        //lblExtado.setVisible(false);
        chkImprimir.setVisible(false);
        //lblMed.setVisible(false);
        

        // Introduccion de datos
       // DefaultCategoryDataset dataset = new DefaultCategoryDataset();

//        int n = 10;
//        for (int j = 1; j < 5; j++) {
//
//            dataset.addValue(8, "GROSOR (+)", "" + j);
//            dataset.addValue(6, "GROSOR (-)", "" + j);
//            dataset.addValue((Math.random() * n) + 1, "IZQUIERDA", "" + j);
//            dataset.addValue((Math.random() * n) + 1, "CENTRO", "" + j);
//            dataset.addValue((Math.random() * n) + 1, "DERECHA", "" + j);
//
//        }
        
//        JFreeChart chart = ChartFactory.createLineChart(
//                "", // Título
//                "Tiempo", // Etiqueta Coordenada X
//                "Grosor", // Etiqueta Coordenada Y
//                dataset, // Datos
//                PlotOrientation.VERTICAL,
//                true, // Muestra la leyenda de los productos (Producto A)
//                true,
//                true
//        );
//dataset.addValue(1, "DERECHA", ""+14);
//        // Mostramos la grafica en pantalla
//        ChartPanel panelin = new ChartPanel(chart);
//        grafica.setLayout(new java.awt.BorderLayout());
//        grafica.add(panelin, BorderLayout.CENTER);
//        grafica.validate();
//dataset.addValue(1, "DERECHA", ""+15);
    }

    public tablaChida getTc() {
        return tc;
    }

    public void setTc(tablaChida tc) {
        this.tc = tc;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblEmpresa = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        btnCargarDatos = new javax.swing.JButton();
        btnIniciarMed = new javax.swing.JButton();
        btnFinalizarMed = new javax.swing.JButton();
        btnGenerarRepo = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtEspesorMM = new javax.swing.JTextField();
        txtEspesorIn = new javax.swing.JTextField();
        txtToleranciaPosMM = new javax.swing.JTextField();
        txtToleranciaPosIn = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtToleranciaNegMM = new javax.swing.JTextField();
        txtToleranciaNegIn = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtRangoMM = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEstilo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtPO = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtPieza = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtTiempoFin = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtTiempoInicio = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtMedidaIzq = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtMedidaCentro = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtMedidaDerecha = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtDensidad = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtMetrosM = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtAnchoM = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtPulsos = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        lblTextNum = new javax.swing.JLabel();
        lblMed = new javax.swing.JLabel();
        lblExtado = new javax.swing.JLabel();
        chkImprimir = new javax.swing.JCheckBox();
        btnCalcularDen = new javax.swing.JButton();
        lblHora = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        chkAPlanchado = new javax.swing.JCheckBox();
        chkDPlanchado = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        txtRecorrer = new javax.swing.JTextField();
        btnRetroceder = new javax.swing.JButton();
        grafica = new javax.swing.JPanel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("PRINCIPAL");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/com/peea/mx/FF/imagenes/icono_opt.png"))); // NOI18N
        setPreferredSize(new java.awt.Dimension(1300, 730));

        lblEmpresa.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblEmpresa.setText("Empresa");

        lblDireccion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblDireccion.setText("Dirección");

        lblTelefono.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblTelefono.setText("telefono");

        btnCargarDatos.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        btnCargarDatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/peea/mx/FF/iconos/lapiz (3).png"))); // NOI18N
        btnCargarDatos.setText("CARGAR DATOS");

        btnIniciarMed.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        btnIniciarMed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/peea/mx/FF/iconos/noticias (5).png"))); // NOI18N
        btnIniciarMed.setText("INICIAR MEDICION");

        btnFinalizarMed.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        btnFinalizarMed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/peea/mx/FF/iconos/lista (2).png"))); // NOI18N
        btnFinalizarMed.setText("TERMINAR MEDICION");
        btnFinalizarMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarMedActionPerformed(evt);
            }
        });

        btnGenerarRepo.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        btnGenerarRepo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/peea/mx/FF/iconos/news-report (3).png"))); // NOI18N
        btnGenerarRepo.setText("GENERAR REPORTE");
        btnGenerarRepo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarRepoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCargarDatos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIniciarMed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFinalizarMed)
                .addGap(5, 5, 5)
                .addComponent(btnGenerarRepo)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnIniciarMed, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCargarDatos)
                        .addComponent(btnFinalizarMed)
                        .addComponent(btnGenerarRepo))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDireccion)))
                .addGap(2, 2, 2)
                .addComponent(lblTelefono)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel5.setText("Espesor: ");

        txtEspesorMM.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        txtEspesorMM.setText("0.0");

        txtEspesorIn.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        txtEspesorIn.setText("0.0");

        txtToleranciaPosMM.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        txtToleranciaPosMM.setText("0.0");

        txtToleranciaPosIn.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        txtToleranciaPosIn.setText("0.0");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel6.setText("Tolerancia (+)");

        txtToleranciaNegMM.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        txtToleranciaNegMM.setText("0.0");

        txtToleranciaNegIn.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        txtToleranciaNegIn.setText("0.0");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel7.setText("Tolerancia (-)");

        txtRangoMM.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        txtRangoMM.setText("0.0");
        txtRangoMM.setFocusable(false);
        txtRangoMM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRangoMMActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel8.setText("% Rango");

        txtEstilo.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        txtEstilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstiloActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel9.setText("Estilo:");

        txtCliente.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        txtCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel10.setText("Cliente:");

        txtPO.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        txtPO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPOActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel11.setText("P.O. #");

        txtPieza.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        txtPieza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPiezaActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel12.setText("Pieza:");

        txtPeso.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        txtPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesoActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel13.setText("Peso:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel4.setText("MESA ");

        jLabel17.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel17.setText("T Fin:");

        txtTiempoFin.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        txtTiempoFin.setToolTipText("");
        txtTiempoFin.setFocusable(false);
        txtTiempoFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTiempoFinActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel18.setText("T Inicio:");

        txtTiempoInicio.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        txtTiempoInicio.setFocusable(false);
        txtTiempoInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTiempoInicioActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel19.setText("Med Izq:");

        txtMedidaIzq.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        txtMedidaIzq.setText("0.0");
        txtMedidaIzq.setFocusable(false);
        txtMedidaIzq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedidaIzqActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel20.setText("Med Centro:");

        txtMedidaCentro.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        txtMedidaCentro.setText("0.0");
        txtMedidaCentro.setFocusable(false);
        txtMedidaCentro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedidaCentroActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel21.setText("Med Der:");

        txtMedidaDerecha.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        txtMedidaDerecha.setText("0.0");
        txtMedidaDerecha.setFocusable(false);
        txtMedidaDerecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedidaDerechaActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel22.setText("Densidad:");

        txtDensidad.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        txtDensidad.setFocusable(false);
        txtDensidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDensidadActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel23.setText("Metros:");

        txtMetrosM.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        txtMetrosM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMetrosMActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel24.setText("Ancho:");

        txtAnchoM.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        txtAnchoM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnchoMActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel27.setText("Pulsos:");

        txtPulsos.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        txtPulsos.setText("0.0");
        txtPulsos.setFocusable(false);
        txtPulsos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPulsosActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel28.setText("MM");

        jLabel29.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel29.setText("Inch");

        lblTextNum.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        lblMed.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblMed.setText("MM");

        lblExtado.setText("jLabel1");
        lblExtado.setToolTipText("");

        btnCalcularDen.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCalcularDen.setText("=");

        lblHora.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblHora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/peea/mx/FF/iconos/reloj-de-pared.png"))); // NOI18N
        lblHora.setText("jLabel16");

        lblFecha.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblFecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/peea/mx/FF/iconos/calendario (2).png"))); // NOI18N
        lblFecha.setText("jLabel15");

        chkAPlanchado.setText("Antes de Planchado");

        chkDPlanchado.setText("Despues de Planchado");

        jLabel1.setText("Retroceder");

        txtRecorrer.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        txtRecorrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRecorrerActionPerformed(evt);
            }
        });

        btnRetroceder.setText("-");
        btnRetroceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetrocederActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtEspesorMM, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtToleranciaPosMM, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtToleranciaPosIn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEspesorIn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRangoMM, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtToleranciaNegMM, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtToleranciaNegIn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTextNum, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel28)
                        .addGap(57, 57, 57)
                        .addComponent(jLabel29)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel9)
                        .addGap(6, 6, 6)
                        .addComponent(txtEstilo, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10))
                                .addComponent(jLabel12)
                                .addComponent(jLabel13))
                            .addGap(6, 6, 6)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtPieza, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPO, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(lblFecha)
                            .addGap(18, 18, 18)
                            .addComponent(lblHora))))
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkDPlanchado)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(chkAPlanchado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chkImprimir)))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtTiempoFin, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtRecorrer, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtTiempoInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRetroceder))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(lblExtado))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel23))
                                .addGap(6, 6, 6)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtMetrosM, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDensidad, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAnchoM, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(btnCalcularDen, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtPulsos, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblMed, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMedidaDerecha))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(jLabel19))
                                    .addComponent(jLabel20))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMedidaCentro, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(txtMedidaIzq, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTextNum, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(jLabel28))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtEspesorMM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEspesorIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtToleranciaPosMM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtToleranciaPosIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtToleranciaNegMM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtToleranciaNegIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRangoMM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtEstilo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblExtado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(txtDensidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel22))
                                                .addGap(11, 11, 11)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(txtMetrosM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel23)))
                                            .addComponent(btnCalcularDen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(12, 12, 12)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtAnchoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel24)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel11)
                                            .addComponent(txtPO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel12)
                                            .addComponent(txtPieza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(jLabel27)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtPulsos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGap(60, 60, 60)
                                            .addComponent(lblMed, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel13))
                                        .addGap(20, 20, 20)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblFecha)
                                            .addComponent(lblHora)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(chkAPlanchado)
                                                    .addComponent(chkImprimir)))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel18)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(chkDPlanchado)
                                            .addComponent(jLabel17)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtTiempoInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1)
                                            .addComponent(btnRetroceder))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtTiempoFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtRecorrer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel19)
                                    .addComponent(txtMedidaIzq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel20)
                                    .addComponent(txtMedidaCentro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtMedidaDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel21))))))
                .addGap(1, 1, 1))
        );

        grafica.setPreferredSize(new java.awt.Dimension(800, 266));

        javax.swing.GroupLayout graficaLayout = new javax.swing.GroupLayout(grafica);
        grafica.setLayout(graficaLayout);
        graficaLayout.setHorizontalGroup(
            graficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        graficaLayout.setVerticalGroup(
            graficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 375, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(grafica, javax.swing.GroupLayout.DEFAULT_SIZE, 986, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(grafica, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEstiloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstiloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstiloActionPerformed

    private void txtClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteActionPerformed

    private void txtPOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPOActionPerformed

    private void txtPiezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPiezaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPiezaActionPerformed

    private void txtPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesoActionPerformed

    private void txtTiempoFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTiempoFinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTiempoFinActionPerformed

    private void txtTiempoInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTiempoInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTiempoInicioActionPerformed

    private void txtMedidaIzqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedidaIzqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedidaIzqActionPerformed

    private void txtMedidaCentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedidaCentroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedidaCentroActionPerformed

    private void txtMedidaDerechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedidaDerechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedidaDerechaActionPerformed

    private void txtDensidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDensidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDensidadActionPerformed

    private void txtMetrosMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMetrosMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMetrosMActionPerformed

    private void txtAnchoMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnchoMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnchoMActionPerformed

    private void txtPulsosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPulsosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPulsosActionPerformed

    private void btnFinalizarMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarMedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFinalizarMedActionPerformed

    private void txtRangoMMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRangoMMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRangoMMActionPerformed

    private void btnGenerarRepoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarRepoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGenerarRepoActionPerformed

    private void txtRecorrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRecorrerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRecorrerActionPerformed

    private void btnRetrocederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetrocederActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRetrocederActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCalcularDen;
    public javax.swing.JButton btnCargarDatos;
    public javax.swing.JButton btnFinalizarMed;
    public javax.swing.JButton btnGenerarRepo;
    public javax.swing.JButton btnIniciarMed;
    public javax.swing.JButton btnRetroceder;
    public javax.swing.JCheckBox chkAPlanchado;
    public javax.swing.JCheckBox chkDPlanchado;
    public javax.swing.JCheckBox chkImprimir;
    public javax.swing.JPanel grafica;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JLabel lblDireccion;
    public javax.swing.JLabel lblEmpresa;
    public javax.swing.JLabel lblExtado;
    public javax.swing.JLabel lblFecha;
    public javax.swing.JLabel lblHora;
    public javax.swing.JLabel lblMed;
    public javax.swing.JLabel lblTelefono;
    public javax.swing.JLabel lblTextNum;
    public javax.swing.JTextField txtAnchoM;
    public javax.swing.JTextField txtCliente;
    public javax.swing.JTextField txtDensidad;
    public javax.swing.JTextField txtEspesorIn;
    public javax.swing.JTextField txtEspesorMM;
    public javax.swing.JTextField txtEstilo;
    public javax.swing.JTextField txtMedidaCentro;
    public javax.swing.JTextField txtMedidaDerecha;
    public javax.swing.JTextField txtMedidaIzq;
    public javax.swing.JTextField txtMetrosM;
    public javax.swing.JTextField txtPO;
    public javax.swing.JTextField txtPeso;
    public javax.swing.JTextField txtPieza;
    public javax.swing.JTextField txtPulsos;
    public javax.swing.JTextField txtRangoMM;
    public javax.swing.JTextField txtRecorrer;
    public javax.swing.JTextField txtTiempoFin;
    public javax.swing.JTextField txtTiempoInicio;
    public javax.swing.JTextField txtToleranciaNegIn;
    public javax.swing.JTextField txtToleranciaNegMM;
    public javax.swing.JTextField txtToleranciaPosIn;
    public javax.swing.JTextField txtToleranciaPosMM;
    // End of variables declaration//GEN-END:variables
}
